Repository nhnacademy-be10-1lluwa/bookstore-front, pull requests merged in 2025-07, with the labels that each got.

#160 feat: 포인트정책 관리기능 구현
  src/main/java/com/nhnacademy/illuwa/admin/controller/AdminPolicyController.java
  src/main/java/com/nhnacademy/illuwa/pointpolicy/client/AdminPointPolicyServiceClient.java
  src/main/java/com/nhnacademy/illuwa/pointpolicy/controller/AdminPointPolicyController.java
  src/main/java/com/nhnacademy/illuwa/pointpolicy/dto/PointPolicyCreateRequest.java
  src/main/java/com/nhnacademy/illuwa/pointpolicy/dto/PointPolicyResponse.java
  src/main/java/com/nhnacademy/illuwa/pointpolicy/dto/PointPolicyUpdateRequest.java
  src/main/java/com/nhnacademy/illuwa/pointpolicy/enums/PointValueType.java
  src/main/java/com/nhnacademy/illuwa/pointpolicy/enums/PolicyStatus.java
  src/main/java/com/nhnacademy/illuwa/pointpolicy/service/AdminPointPolicyService.java
  src/main/resources/static/css/policy/_policy_form.css
  src/main/resources/static/css/policy/_policy_view_list.css
  src/main/resources/templates/admin/policy/point.html
  src/main/resources/templates/admin/policy/point_policy_form.html
  src/main/resources/templates/admin/policy/point_policy_view_list.html
Labels: 🎨 UI, 🌈 frontend

#183 feat: 포인트정책 구현 완료
  src/main/java/com/nhnacademy/illuwa/member/enums/Role.java
  src/main/java/com/nhnacademy/illuwa/pointpolicy/controller/AdminPointPolicyController.java
  src/main/java/com/nhnacademy/illuwa/pointpolicy/dto/PointPolicyResponse.java
  src/main/java/com/nhnacademy/illuwa/pointpolicy/service/AdminPointPolicyService.java
  src/main/resources/static/css/page/_point_history.css
  src/main/resources/templates/admin/policy/point_policy_form.html
  src/main/resources/templates/admin/policy/point_policy_view_list.html
  src/main/resources/templates/mypage/section/point_history.html
Labels: 🎨 UI, 🌈 frontend

#198 [FEAT] 리뷰 쓰기/수정 프론트
  pom.xml
  src/main/java/com/nhnacademy/illuwa/config/FeignClientConfig.java
  src/main/java/com/nhnacademy/illuwa/review/client/ReviewServiceClient.java
  src/main/java/com/nhnacademy/illuwa/review/controller/ReviewController.java
  src/main/java/com/nhnacademy/illuwa/review/dto/ReviewRequest.java
  src/main/java/com/nhnacademy/illuwa/review/service/ReviewService.java
  src/main/resources/templates/review/reviewForm.html
Labels: 🌈 frontend

#203 [FEAT] 도서 관리 페이지 pagination 적용
  pom.xml
  src/main/java/com/nhnacademy/illuwa/FrontServerApplication.java
  src/main/java/com/nhnacademy/illuwa/admin/controller/AdminBookController.java
  src/main/java/com/nhnacademy/illuwa/book/client/ProductServiceClient.java
  src/main/java/com/nhnacademy/illuwa/book/dto/BookDetailWithExtraInfoResponse.java
  src/main/java/com/nhnacademy/illuwa/book/dto/FinalAladinBookRegisterRequest.java
  src/main/java/com/nhnacademy/illuwa/category/controller/AdminCategoryController.java
  src/main/resources/templates/admin/book/manage.html
Labels: 🌈 frontend, 🧹 cleanup

#205 [FEAT] 카테고리 Pagenation 구현
  src/main/java/com/nhnacademy/illuwa/admin/controller/AdminBookController.java
  src/main/java/com/nhnacademy/illuwa/book/dto/BookDetailWithExtraInfoResponse.java
  src/main/java/com/nhnacademy/illuwa/category/client/CategoryServiceClient.java
  src/main/java/com/nhnacademy/illuwa/category/controller/AdminCategoryController.java
  src/main/java/com/nhnacademy/illuwa/category/controller/CateogoryController.java
  src/main/java/com/nhnacademy/illuwa/category/dto/CategoryFlatResponse.java
  src/main/java/com/nhnacademy/illuwa/category/dto/CategoryResponse.java
  src/main/resources/templates/admin/category/manage.html
Labels: ♻️ refactor, 🌈 frontend

#209 [FEAT] 도서 태그
  src/main/java/com/nhnacademy/illuwa/admin/controller/AdminBookController.java
  src/main/java/com/nhnacademy/illuwa/admin/controller/AdminCategoryController.java
  src/main/java/com/nhnacademy/illuwa/admin/controller/AdminTagController.java
  src/main/java/com/nhnacademy/illuwa/book/dto/BookDetailWithExtraInfoResponse.java
  src/main/java/com/nhnacademy/illuwa/tag/client/TagServiceClient.java
  src/main/java/com/nhnacademy/illuwa/tag/dto/PageResponse.java
  src/main/java/com/nhnacademy/illuwa/tag/dto/TagCreateRequest.java
  src/main/java/com/nhnacademy/illuwa/tag/dto/TagResponse.java
  src/main/resources/templates/admin/book/books.html
  src/main/resources/templates/admin/book/manage.html
  src/main/resources/templates/admin/tag/manage.html
Labels: ♻️ refactor, 🌈 frontend

#206 Feat: #166 회원 바로 주문하기 추가
  src/main/java/com/nhnacademy/illuwa/coupon/dto/MemberCouponResponse.java
  src/main/java/com/nhnacademy/illuwa/order/client/OrderServiceClient.java
  src/main/java/com/nhnacademy/illuwa/order/controller/MemberOrderController.java
  src/main/java/com/nhnacademy/illuwa/order/dto/BookItemOrderDto.java
  src/main/java/com/nhnacademy/illuwa/order/dto/OrderCreateResponse.java
  src/main/java/com/nhnacademy/illuwa/order/dto/OrderItemResponseDto.java
  src/main/java/com/nhnacademy/illuwa/order/dto/member/MemberAddressDto.java
  src/main/java/com/nhnacademy/illuwa/order/dto/member/MemberOrderDirectRequest.java
  src/main/java/com/nhnacademy/illuwa/order/dto/member/MemberOrderInitDirectResponse.java
  src/main/java/com/nhnacademy/illuwa/order/dto/orderRequest/OrderItemDto.java
  src/main/java/com/nhnacademy/illuwa/order/service/OrderService.java
  src/main/resources/static/js/order/order_member_form.js
  src/main/resources/templates/book/detail.html
  src/main/resources/templates/order/order_member_form.html
  src/main/resources/templates/order/order_view.html
Labels: 🌈 frontend

#210 Feat: #207 비회원 바로 주문 구현
  src/main/java/com/nhnacademy/illuwa/coupon/controller/MyCouponController.java
  src/main/java/com/nhnacademy/illuwa/coupon/dto/MemberCouponResponse.java
  src/main/java/com/nhnacademy/illuwa/order/client/OrderServiceClient.java
  src/main/java/com/nhnacademy/illuwa/order/controller/GuestOrderController.java
  src/main/java/com/nhnacademy/illuwa/order/controller/MemberOrderController.java
  src/main/java/com/nhnacademy/illuwa/order/dto/OrderItemResponseDto.java
  src/main/java/com/nhnacademy/illuwa/order/dto/guest/GuestOrderDirectRequest.java
  src/main/java/com/nhnacademy/illuwa/order/dto/guest/GuestOrderInitDirectResponse.java
  src/main/java/com/nhnacademy/illuwa/order/service/OrderService.java
  src/main/resources/static/css/order/address_modal.css
  src/main/resources/static/css/order/order_form.css
  src/main/resources/static/css/order/order_view.css
  src/main/resources/static/js/order/order_guest_form.js
  src/main/resources/static/js/order/order_member_form.js
  src/main/resources/templates/book/detail.html
  src/main/resources/templates/order/order_guest_form.html
  src/main/resources/templates/order/order_member_form.html
  src/main/resources/templates/order/order_view.html
Labels: ♻️ refactor, 🌈 frontend

#211 feat: #194 휴면회원 인증 구현
  src/main/java/com/nhnacademy/illuwa/auth/client/InactiveVerificationServiceClient.java
  src/main/java/com/nhnacademy/illuwa/auth/controller/LoginController.java
  src/main/java/com/nhnacademy/illuwa/auth/dto/InactiveCheckResponse.java
  src/main/java/com/nhnacademy/illuwa/auth/dto/MemberLoginRequest.java
  src/main/java/com/nhnacademy/illuwa/auth/dto/SendVerificationRequest.java
  src/main/java/com/nhnacademy/illuwa/auth/service/InactiveVerificationService.java
  src/main/java/com/nhnacademy/illuwa/config/SecurityConfig.java
  src/main/java/com/nhnacademy/illuwa/member/client/MemberServiceClient.java
  src/main/java/com/nhnacademy/illuwa/member/enums/Status.java
  src/main/resources/static/css/page/_inactive-verfication.css
  src/main/resources/static/js/auth/inactive-verification.js
  src/main/resources/templates/auth/inactive-verification.html
  src/main/resources/templates/user/inactive_certificate.html
Labels: 🌈 frontend

#217 refactor: page dto 리팩토링
  src/main/java/com/nhnacademy/illuwa/admin/controller/AdminTagController.java
  src/main/java/com/nhnacademy/illuwa/common/dto/PageResponse.java
  src/main/java/com/nhnacademy/illuwa/member/client/AdminMemberServiceClient.java
  src/main/java/com/nhnacademy/illuwa/member/controller/AdminMemberController.java
  src/main/java/com/nhnacademy/illuwa/member/service/AdminMemberService.java
  src/main/java/com/nhnacademy/illuwa/memberaddress/client/MemberAddressServiceClient.java
  src/main/java/com/nhnacademy/illuwa/memberaddress/controller/MemberAddressController.java
  src/main/java/com/nhnacademy/illuwa/memberaddress/dto/PageResponse.java
  src/main/java/com/nhnacademy/illuwa/order/controller/OrderListController.java
  src/main/java/com/nhnacademy/illuwa/pointhistory/client/PointHistoryServiceClient.java
  src/main/java/com/nhnacademy/illuwa/pointhistory/controller/PointHistoryController.java
  src/main/java/com/nhnacademy/illuwa/pointhistory/service/PointHistoryService.java
  src/main/java/com/nhnacademy/illuwa/review/controller/ReviewController.java
  src/main/java/com/nhnacademy/illuwa/review/dto/PageResponse.java
  src/main/java/com/nhnacademy/illuwa/tag/client/TagServiceClient.java
  src/main/java/com/nhnacademy/illuwa/tag/dto/PageResponse.java
Labels: ♻️ refactor

#232 Feat: #231 장바구니 주문하기 구현
  src/main/java/com/nhnacademy/illuwa/admin/controller/AdminOrderController.java
  src/main/java/com/nhnacademy/illuwa/order/client/OrderServiceClient.java
  src/main/java/com/nhnacademy/illuwa/order/controller/MemberOrderController.java
  src/main/java/com/nhnacademy/illuwa/order/dto/member/MemberOrderCartRequest.java
  src/main/java/com/nhnacademy/illuwa/order/dto/member/MemberOrderInitFromCartResponse.java
  src/main/java/com/nhnacademy/illuwa/order/dto/orderRequest/OrderItemDto.java
  src/main/java/com/nhnacademy/illuwa/order/service/OrderService.java
  src/main/resources/static/js/order/order_member_cart_form.js
  src/main/resources/templates/order/order_cart_view.html
  src/main/resources/templates/order/order_member_cart_form.html
  src/main/resources/templates/order/order_member_form.html
  src/main/resources/templates/user/cart.html
Labels: 🌈 frontend

#243 Feat: #231 회원 장바구니 주문하기 구현
  src/main/java/com/nhnacademy/illuwa/order/client/OrderServiceClient.java
  src/main/java/com/nhnacademy/illuwa/order/controller/MemberOrderController.java
  src/main/java/com/nhnacademy/illuwa/order/dto/member/MemberCouponDto.java
  src/main/java/com/nhnacademy/illuwa/order/dto/member/MemberOrderInitDirectResponse.java
  src/main/java/com/nhnacademy/illuwa/order/dto/member/MemberOrderInitFromCartResponse.java
  src/main/java/com/nhnacademy/illuwa/order/dto/orderRequest/MemberOrderInfo.java
  src/main/resources/static/js/order/order_member_cart_form.js
  src/main/resources/templates/order/order_cart_view.html
  src/main/resources/templates/order/order_member_cart_form.html
  src/main/resources/templates/order/order_member_form.html
  src/main/resources/templates/order/order_view.html
Labels: ♻️ refactor, 🌈 frontend

#263 [FEAT] 도서 검색
  src/main/java/com/nhnacademy/illuwa/main/controller/HomeController.java
  src/main/java/com/nhnacademy/illuwa/search/client/BookSearchClient.java
  src/main/java/com/nhnacademy/illuwa/search/controller/BookSearchController.java
  src/main/java/com/nhnacademy/illuwa/search/dto/BookDocument.java
  src/main/java/com/nhnacademy/illuwa/search/service/BookSearchService.java
  src/main/resources/templates/book/search_result.html
  src/main/resources/templates/layout/layout.html
Labels: ♻️ refactor, 🎨 UI, 🌈 frontend

#268 refactor: #266 메인 페이지 비회원 로그인 삭제
  src/main/resources/templates/home.html
Labels: ♻️ refactor, 🌈 frontend

#265 [FEAT] 리뷰 프론트
  src/main/java/com/nhnacademy/illuwa/admin/controller/AdminOrderController.java
  src/main/java/com/nhnacademy/illuwa/book/controller/BookController.java
  src/main/java/com/nhnacademy/illuwa/book/controller/BookInfoController.java
  src/main/java/com/nhnacademy/illuwa/book/controller/BookListController.java
  src/main/java/com/nhnacademy/illuwa/book/service/BookService.java
  src/main/java/com/nhnacademy/illuwa/order/controller/OrderDetailController.java
  src/main/java/com/nhnacademy/illuwa/order/controller/OrderListController.java
  src/main/java/com/nhnacademy/illuwa/review/client/ReviewServiceClient.java
  src/main/java/com/nhnacademy/illuwa/review/controller/CommentController.java
  src/main/java/com/nhnacademy/illuwa/review/controller/ReviewController.java
  src/main/java/com/nhnacademy/illuwa/review/controller/ReviewLikeController.java
  src/main/java/com/nhnacademy/illuwa/review/dto/CommentRequest.java
  src/main/java/com/nhnacademy/illuwa/review/dto/ReviewLikeResponse.java
  src/main/java/com/nhnacademy/illuwa/review/dto/UploadResponse.java
  src/main/java/com/nhnacademy/illuwa/review/service/CommentService.java
  src/main/java/com/nhnacademy/illuwa/review/service/ReviewLikeService.java
  src/main/java/com/nhnacademy/illuwa/review/service/ReviewService.java
  src/main/resources/static/js/review/review_comment.js
  src/main/resources/static/js/review/review_like.js
  src/main/resources/templates/admin/order/order_detail.html
  src/main/resources/templates/book/book_info.html
  src/main/resources/templates/book/book_list.html
  src/main/resources/templates/book/detail.html
  src/main/resources/templates/mypage/mypage.html
  src/main/resources/templates/order/order_detail.html
  src/main/resources/templates/order/order_list.html
  src/main/resources/templates/payment/payment.html
Labels: 🌈 frontend

#274 [FEAT] 리뷰작성자 이름으로 가져오게 변경
  src/main/java/com/nhnacademy/illuwa/book/controller/BookController.java
  src/main/java/com/nhnacademy/illuwa/member/client/MemberServiceClient.java
  src/main/java/com/nhnacademy/illuwa/member/service/MemberService.java
  src/main/resources/templates/book/detail.html
Labels: 🌈 frontend

#277 feature/272-reviewer-name
  src/main/java/com/nhnacademy/illuwa/book/controller/BookController.java
  src/main/java/com/nhnacademy/illuwa/member/client/MemberServiceClient.java
  src/main/java/com/nhnacademy/illuwa/member/service/MemberService.java
Labels: 🌈 frontend

#292 refactor: html 수정
  src/main/java/com/nhnacademy/illuwa/admin/controller/AdminOrderController.java
  src/main/resources/templates/admin/order/order_detail.html
  src/main/resources/templates/book/detail.html
  src/main/resources/templates/order/order_cart_view.html
  src/main/resources/templates/order/order_detail.html
  src/main/resources/templates/order/order_guest_form.html
  src/main/resources/templates/order/order_member_form.html
Labels: ♻️ refactor, 🌈 frontend

#308 refactor: #307 휴면회원 api 수정
  src/main/java/com/nhnacademy/illuwa/auth/client/InactiveVerificationServiceClient.java
  src/main/java/com/nhnacademy/illuwa/auth/controller/InactiveVerificationController.java
  src/main/resources/static/js/auth/inactive-verification.js
Labels: ♻️ refactor

#306 [FEAT] 도서 검색 이후 도서 상세페이지 이동 api 추가
  src/main/java/com/nhnacademy/illuwa/book/client/ProductServiceClient.java
  src/main/java/com/nhnacademy/illuwa/book/controller/BookController.java
  src/main/java/com/nhnacademy/illuwa/book/service/BookService.java
  src/main/resources/static/js/book/booklist.js
  src/main/resources/static/js/home.js
  src/main/resources/templates/book/search_result.html
Labels: ♻️ refactor, 🌈 frontend

#323 Feat: #322 member grade
  src/main/java/com/nhnacademy/illuwa/admin/controller/AdminOrderController.java
  src/main/java/com/nhnacademy/illuwa/order/client/OrderServiceClient.java
  src/main/java/com/nhnacademy/illuwa/order/controller/MemberOrderController.java
  src/main/java/com/nhnacademy/illuwa/order/service/OrderService.java
  src/main/resources/static/js/order/order_guest_form.js
  src/main/resources/static/js/order/order_member_cart_form.js
  src/main/resources/static/js/order/order_member_form.js
  src/main/resources/templates/admin/member/member_list.html
  src/main/resources/templates/order/order_detail.html
  src/main/resources/templates/order/order_guest_form.html
  src/main/resources/templates/order/order_member_form.html
Labels: ♻️ refactor, 🌈 frontend

#317 [FIX] 북마크->좋아요 한 도서
  src/main/java/com/nhnacademy/illuwa/book/controller/BookController.java
  src/main/java/com/nhnacademy/illuwa/booklike/client/BookLikeServiceClient.java
  src/main/java/com/nhnacademy/illuwa/booklike/controller/BookLikeController.java
  src/main/java/com/nhnacademy/illuwa/booklike/dto/BookLikeResponse.java
  src/main/java/com/nhnacademy/illuwa/booklike/service/BookLikeService.java
  src/main/java/com/nhnacademy/illuwa/bookmark/controller/BookMarkController.java
  src/main/java/com/nhnacademy/illuwa/bookmark/service/BookMarkService.java
  src/main/java/com/nhnacademy/illuwa/order/controller/OrderDetailController.java
  src/main/java/com/nhnacademy/illuwa/review/client/ReviewServiceClient.java
  src/main/java/com/nhnacademy/illuwa/review/service/ReviewLikeService.java
  src/main/resources/static/js/review/review_like.js
  src/main/resources/templates/book/detail.html
  src/main/resources/templates/layout/mypage-sidebar.html
  src/main/resources/templates/mypage/section/book_likes.html
  src/main/resources/templates/order/order_detail.html
  src/main/resources/templates/review/review_form.html
Labels: ♻️ refactor

#326 bugfix: html 링크 버그
  src/main/resources/templates/home.html
  src/main/resources/templates/layout/header.html
Labels: 🐛bug

#341 Feat: #338 내가 쓴 리뷰 페이지
  src/main/java/com/nhnacademy/illuwa/pointhistory/enums/PointHistoryType.java
  src/main/java/com/nhnacademy/illuwa/pointhistory/enums/PointReason.java
  src/main/java/com/nhnacademy/illuwa/review/client/ReviewServiceClient.java
  src/main/java/com/nhnacademy/illuwa/review/controller/ReviewController.java
  src/main/java/com/nhnacademy/illuwa/review/service/ReviewService.java
  src/main/resources/templates/layout/mypage-sidebar.html
  src/main/resources/templates/mypage/section/point_history.html
  src/main/resources/templates/mypage/section/review_history.html
  src/main/resources/templates/review/review_form.html
  src/test/java/com/nhnacademy/illuwa/member/service/AdminMemberServiceTest.java
Labels: 🌈 frontend

#340 cleanup: 댓글 기능 삭제
  src/main/java/com/nhnacademy/illuwa/book/controller/BookController.java
  src/main/java/com/nhnacademy/illuwa/review/client/ReviewServiceClient.java
  src/main/java/com/nhnacademy/illuwa/review/controller/CommentController.java
  src/main/java/com/nhnacademy/illuwa/review/dto/CommentRequest.java
  src/main/java/com/nhnacademy/illuwa/review/dto/CommentResponse.java
  src/main/java/com/nhnacademy/illuwa/review/service/CommentService.java
  src/main/resources/static/js/review/review_comment.js
  src/main/resources/templates/book/detail.html
Labels: 🐛bug, 🌈 frontend, 🧹 cleanup

#344 Feat/342 클라이언트, 서비스 코드 패키지 경로 수정
  src/main/java/com/nhnacademy/illuwa/admin/controller/AdminOrderController.java
  src/main/java/com/nhnacademy/illuwa/admin/controller/AdminPackagingController.java
  src/main/java/com/nhnacademy/illuwa/order/client/AdminOrderClient.java
  src/main/java/com/nhnacademy/illuwa/order/client/CommonOrderClient.java
  src/main/java/com/nhnacademy/illuwa/order/client/GuestOrderClient.java
  src/main/java/com/nhnacademy/illuwa/order/client/MemberOrderClient.java
  src/main/java/com/nhnacademy/illuwa/order/client/OrderServiceClient.java
  src/main/java/com/nhnacademy/illuwa/order/client/PackagingClient.java
  src/main/java/com/nhnacademy/illuwa/order/controller/GuestOrderController.java
  src/main/java/com/nhnacademy/illuwa/order/controller/MemberOrderController.java
  src/main/java/com/nhnacademy/illuwa/order/controller/OrderDetailController.java
  src/main/java/com/nhnacademy/illuwa/order/controller/OrderListController.java
  src/main/java/com/nhnacademy/illuwa/order/dto/types/OrderStatus.java
  src/main/java/com/nhnacademy/illuwa/order/service/AdminOrderService.java
  src/main/java/com/nhnacademy/illuwa/order/service/CommonOrderService.java
  src/main/java/com/nhnacademy/illuwa/order/service/GuestOrderService.java
  src/main/java/com/nhnacademy/illuwa/order/service/MemberOrderService.java
  src/main/java/com/nhnacademy/illuwa/order/service/OrderService.java
  src/main/java/com/nhnacademy/illuwa/order/service/OrderStatusMemberService.java
  src/main/java/com/nhnacademy/illuwa/order/service/PackagingService.java
  src/main/java/com/nhnacademy/illuwa/order/service/impl/AdminOrderServiceImpl.java
  src/main/java/com/nhnacademy/illuwa/order/service/impl/CommonOrderServiceImpl.java
  src/main/java/com/nhnacademy/illuwa/order/service/impl/GuestOrderServiceImpl.java
  src/main/java/com/nhnacademy/illuwa/order/service/impl/MemberOrderServiceImpl.java
  src/main/java/com/nhnacademy/illuwa/order/service/impl/PackagingServiceImpl.java
  src/main/java/com/nhnacademy/illuwa/payment/controller/PaymentController.java
  src/main/resources/templates/admin/admin_home.html
Labels: ♻️ refactor, 🧹 cleanup

#351 bugfix: #350 도서 좋아요 버그 해결
  src/main/java/com/nhnacademy/illuwa/booklike/client/BookLikeServiceClient.java
  src/main/java/com/nhnacademy/illuwa/booklike/controller/BookLikeController.java
  src/main/resources/static/css/page/book/detail.css
  src/main/resources/static/css/page/member/book-likes.css
  src/main/resources/static/css/page/review/_review_form.css
  src/main/resources/templates/book/detail.html
  src/main/resources/templates/mypage/section/book_likes.html
  src/main/resources/templates/review/review_form.html
Labels: 🐛bug, 🎨 UI

#367 refactor: jwt 쿠키 로직 수정
  src/main/java/com/nhnacademy/illuwa/auth/utils/JwtCookieUtil.java
Labels: ♻️ refactor

#365 refactor: #364 자잘한 코드 수정
  src/main/java/com/nhnacademy/illuwa/admin/controller/AdminOrderController.java
  src/main/java/com/nhnacademy/illuwa/order/client/CommonOrderClient.java
  src/main/java/com/nhnacademy/illuwa/order/client/GuestOrderClient.java
  src/main/java/com/nhnacademy/illuwa/order/controller/member/command/MemberOrderStatusController.java
  src/main/java/com/nhnacademy/illuwa/order/dto/command/create/GuestOrderDirectRequest.java
  src/main/java/com/nhnacademy/illuwa/order/dto/command/status/ReturnRequestCreateRequest.java
  src/main/java/com/nhnacademy/illuwa/order/service/CommonOrderService.java
  src/main/java/com/nhnacademy/illuwa/order/service/impl/CommonOrderServiceImpl.java
  src/main/java/com/nhnacademy/illuwa/payment/controller/PaymentController.java
Labels: ♻️ refactor

#360 [FEAT] 도서 등록 form 개선 - toastUI 적용
  src/main/resources/templates/admin/book/book_register.html
  src/main/resources/templates/admin/book/book_register_api.html
Labels: ✅ test, 🌈 frontend

#407 refactor: #393 로그인 로직 수정(휴면회원)
  src/main/java/com/nhnacademy/illuwa/auth/client/AuthClient.java
  src/main/java/com/nhnacademy/illuwa/auth/client/InactiveVerificationServiceClient.java
  src/main/java/com/nhnacademy/illuwa/auth/controller/InactiveVerificationController.java
  src/main/java/com/nhnacademy/illuwa/auth/controller/LoginController.java
  src/main/java/com/nhnacademy/illuwa/auth/dto/MemberLoginResponse.java
  src/main/java/com/nhnacademy/illuwa/auth/dto/message/InactiveCheckResponse.java
  src/main/java/com/nhnacademy/illuwa/auth/dto/message/SendMessageResponse.java
  src/main/java/com/nhnacademy/illuwa/auth/dto/message/SendVerificationRequest.java
  src/main/java/com/nhnacademy/illuwa/auth/dto/message/VerifyCodeRequest.java
  src/main/java/com/nhnacademy/illuwa/auth/dto/message/VerifyCodeResponse.java
  src/main/java/com/nhnacademy/illuwa/auth/service/InactiveVerificationService.java
  src/main/resources/static/js/auth/inactive-verification.js
  src/main/resources/templates/auth/inactive-verification.html
  src/test/java/com/nhnacademy/illuwa/auth/client/AuthClientTest.java
  src/test/java/com/nhnacademy/illuwa/auth/client/InactiveVerificationServiceClientTest.java
  src/test/java/com/nhnacademy/illuwa/auth/service/InactiveVerificationServiceTest.java
Labels: ♻️ refactor, 🎨 UI, 🌈 frontend

#409 [FIX] 도서 수정 - 포장 여부 반영 Issue 해결
  src/main/resources/templates/admin/book/book_update.html
Labels: 🐛bug

#418 [FEAT] 리뷰 이미지 위치 조정
  src/main/java/com/nhnacademy/illuwa/review/client/ReviewServiceClient.java
  src/main/resources/static/css/page/book/detail.css
  src/main/resources/static/css/page/review/_review_form.css
  src/main/resources/templates/book/detail.html
  src/main/resources/templates/review/review_form.html
Labels: 🎨 UI, 🌈 frontend

#423 bug fix: post 주소 변경
  src/main/java/com/nhnacademy/illuwa/admin/controller/AdminOrderController.java
  src/main/java/com/nhnacademy/illuwa/order/dto/types/OrderStatus.java
  src/main/java/com/nhnacademy/illuwa/order/dto/types/ReturnReason.java
  src/main/resources/templates/admin/order/order_detail.html
  src/main/resources/templates/order/order_detail.html
Labels: 🐛bug, ♻️ refactor

#432 [FEAT] 이미지 깨짐 오류 수정
  src/main/java/com/nhnacademy/illuwa/book/client/ProductServiceClient.java
  src/main/java/com/nhnacademy/illuwa/review/service/ReviewService.java
  src/main/resources/static/css/page/review/_review_form.css
  src/main/resources/templates/mypage/section/review_history.html
  src/main/resources/templates/review/review_form.html
Labels: 🐛bug, 🎨 UI, 🌈 frontend

#445 refactor: API 주소 변경
  src/main/java/com/nhnacademy/illuwa/order/client/AdminOrderClient.java
  src/main/java/com/nhnacademy/illuwa/order/client/CommonOrderClient.java
  src/main/java/com/nhnacademy/illuwa/order/client/GuestOrderClient.java
  src/main/java/com/nhnacademy/illuwa/order/client/MemberOrderClient.java
  src/main/java/com/nhnacademy/illuwa/order/client/PackagingClient.java
Labels: ♻️ refactor

#446 fix: 서버 이미지 깨지는 오류 2차
  src/main/java/com/nhnacademy/illuwa/review/service/ReviewService.java
  src/main/resources/templates/review/review_form.html
Labels: 🐛bug
